eno =int(input('Enter Employee number:'))
ename =(input('Enter Employee Name:'))
esal=int(input('Enter Employee salary:'))
eaddr =(input('Enter Employee address:'))
married=bool(input('Enter Employee married status:[True][False]'))

print('Please confirm Information..')
print('Employee Number:',eno)
print('Employee Name:',ename)
print('Employee Salary:',esal)
print('Employee Address:',eaddr)	
print('Employee Marriage:',married)
